# Generated by Django 5.2.4 on 2025-08-08 05:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="brand",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="historicalbrand",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
