# Generated by Django 5.2.4 on 2025-08-08 06:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0004_category_historicalcategory_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="historicalcategory",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
