# Generated by Django 5.2.4 on 2025-07-09 17:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PageItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "icon_name",
                    models.CharField(
                        blank=True,
                        help_text="Static filename (e.g. 'warehouse.png') under your static folder",
                        max_length=255,
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        help_text="Leave blank for top-level pages",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="children",
                        to="web_pages.pageitem",
                    ),
                ),
            ],
            options={
                "verbose_name": "Web Page Item",
                "verbose_name_plural": "Web Page Items",
                "ordering": ("parent__id", "name"),
            },
        ),
    ]
