# Generated by Django 5.2.4 on 2025-07-10 06:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("web_pages", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="pageitem",
            options={
                "ordering": ["parent__id", "order", "name"],
                "verbose_name": "Web Page Item",
                "verbose_name_plural": "Web Page Items",
            },
        ),
        migrations.AddField(
            model_name="pageitem",
            name="order",
            field=models.PositiveIntegerField(
                default=0, help_text="Display order (smaller numbers come first)"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="pageitem",
            unique_together={("parent", "name")},
        ),
    ]
