# Generated by Django 5.2.4 on 2025-07-10 08:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("web_pages", "0002_alter_pageitem_options_pageitem_order_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="pageitem",
            name="redirect_url",
            field=models.CharField(
                blank=True,
                help_text="Optional path (e.g. '/catalog/home/') or URL name",
                max_length=255,
            ),
        ),
    ]
