# Generated by Django 5.2.4 on 2025-07-08 20:51

import department.models
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DepartmentCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="DepartmentRegion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="DepartmentType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Department",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "draft_quotation",
                    models.FileField(
                        blank=True,
                        help_text="Upload a DOCX up to 100 MB.",
                        null=True,
                        upload_to="departments/draft_quotations/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=["docx"]
                            ),
                            department.models.validate_file_size,
                        ],
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        help_text="Leave blank for a top-level department",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="department.department",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        help_text="Optional category",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="department.departmentcategory",
                    ),
                ),
                (
                    "region",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="department.departmentregion",
                    ),
                ),
                (
                    "dept_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="department.departmenttype",
                    ),
                ),
            ],
            options={
                "unique_together": {("parent", "name")},
            },
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_on_duty", models.BooleanField(default=False)),
                (
                    "job_title",
                    models.CharField(
                        blank=True,
                        default="Not Defined Yet",
                        help_text="User’s job title (e.g. Sales Manager).",
                        max_length=100,
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OnDutyChangeLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("old_value", models.BooleanField()),
                ("new_value", models.BooleanField()),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "who_changed",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="duty_changes_made",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "target_profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="duty_change_logs",
                        to="department.userprofile",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ApprovalLimit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "level",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (3, "L3 (Rep)"),
                            (2, "L2 (Manager)"),
                            (1, "L1 (Director)"),
                        ]
                    ),
                ),
                (
                    "max_amount",
                    models.PositiveIntegerField(
                        help_text="Max quote total auto-approved"
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        help_text="Department this limit applies to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="approval_limits",
                        to="department.department",
                    ),
                ),
            ],
            options={
                "verbose_name": "Approval Limit",
                "verbose_name_plural": "Approval Limits",
                "ordering": ["department__name", "-level"],
                "unique_together": {("department", "level")},
            },
        ),
        migrations.CreateModel(
            name="DepartmentMembership",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "level",
                    models.PositiveSmallIntegerField(
                        choices=[(1, "Level 1"), (2, "Level 2"), (3, "Level 3")]
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="department.department",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("user", "department", "level")},
            },
        ),
    ]
