# Generated by Django 5.2.4 on 2025-07-09 11:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("department", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="departmentmembership",
            options={"ordering": ["department__name", "level"]},
        ),
        migrations.AlterUniqueTogether(
            name="departmentmembership",
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name="department",
            name="draft_quotation",
        ),
        migrations.AddField(
            model_name="department",
            name="members",
            field=models.ManyToManyField(
                related_name="departments",
                through="department.DepartmentMembership",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="departmentmembership",
            name="department",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="department_memberships",
                to="department.department",
            ),
        ),
        migrations.AlterField(
            model_name="departmentmembership",
            name="level",
            field=models.PositiveSmallIntegerField(
                choices=[(1, "L1 (Top)"), (2, "L2 (Mid)"), (3, "L3 (Base)")],
                default=3,
                help_text="1=Top, 2=Mid, 3=Base",
            ),
        ),
        migrations.AlterField(
            model_name="departmentmembership",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="department_memberships",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="departmentmembership",
            unique_together={("user", "department")},
        ),
    ]
