# Generated by Django 5.2.4 on 2025-07-09 18:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "department",
            "0003_remove_department_category_alter_approvallimit_level_and_more",
        ),
        ("web_pages", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="departmentsubtype",
            name="page_items",
            field=models.ManyToManyField(
                blank=True,
                help_text="Which top-level web pages map here?",
                related_name="subtypes",
                to="web_pages.pageitem",
            ),
        ),
    ]
